'use client';

import { formatWealth } from '@/data/global-wealth';

interface WealthShareCardProps {
  percentile: number;
  wealth: number;
  currency: 'KRW' | 'USD';
  exchangeRate?: number;
}

export default function WealthShareCard({
  percentile,
  wealth,
  currency,
  exchangeRate = 1350
}: WealthShareCardProps) {

  const getWealthLabel = (percentile: number): string => {
    if (percentile >= 99.9) return "Ultra High Net Worth";
    if (percentile >= 99.5) return "Very High Net Worth";
    if (percentile >= 99) return "High Net Worth";
    if (percentile >= 95) return "상위 5%";
    if (percentile >= 90) return "상위 10%";
    if (percentile >= 75) return "중상위층";
    if (percentile >= 50) return "중산층";
    if (percentile >= 25) return "중하위층";
    return "하위층";
  };

  const wealthInUSD = currency === 'KRW' ? wealth / exchangeRate : wealth;
  const formattedWealth = currency === 'KRW' ?
    `₩${wealth.toLocaleString()}` :
    formatWealth(wealth);

  const rank = Math.round((100 - percentile) * 80000000);

  return (
    <div className="w-[1200px] h-[630px] relative overflow-hidden">
      {/* 배경 그라디언트 */}
      <div className="absolute inset-0 bg-gradient-to-br from-indigo-600 via-purple-700 to-pink-600" />

      {/* 데코레이션 원들 */}
      <div className="absolute -top-20 -right-20 w-80 h-80 bg-white/10 rounded-full blur-3xl" />
      <div className="absolute -bottom-32 -left-32 w-96 h-96 bg-white/5 rounded-full blur-3xl" />
      <div className="absolute top-20 left-20 w-32 h-32 bg-yellow-300/20 rounded-full blur-2xl" />

      {/* 메인 컨텐츠 */}
      <div className="relative z-10 flex flex-col justify-center items-center h-full px-16 text-white">

        {/* 헤더 */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-3 mb-6">
            <div className="w-12 h-12 bg-white/20 backdrop-blur-sm rounded-xl flex items-center justify-center">
              <svg className="w-7 h-7 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
            </div>
            <h1 className="text-2xl font-bold tracking-wide">PayLens</h1>
          </div>
          <h2 className="text-3xl font-light text-white/90">글로벌 자산 순위</h2>
        </div>

        {/* 메인 결과 */}
        <div className="bg-white/15 backdrop-blur-md rounded-3xl p-12 text-center border border-white/20 shadow-2xl mb-8">

          {/* 퍼센타일 */}
          <div className="mb-8">
            <div className="text-7xl font-bold mb-2 bg-gradient-to-r from-yellow-300 to-orange-300 bg-clip-text text-transparent">
              상위 {(100 - percentile).toFixed(1)}%
            </div>
            <div className="text-xl text-white/80">
              전 세계 80억 명 중
            </div>
          </div>

          {/* 순위 */}
          <div className="mb-8 p-6 bg-white/10 rounded-2xl">
            <div className="text-4xl font-bold text-yellow-300 mb-2">
              #{rank.toLocaleString()}위
            </div>
            <div className="text-lg text-white/70">
              예상 글로벌 순위
            </div>
          </div>

          {/* 자산 정보 */}
          <div className="grid grid-cols-2 gap-6">
            <div className="text-center">
              <div className="text-2xl font-semibold text-white mb-1">
                {formattedWealth}
              </div>
              <div className="text-sm text-white/60">
                순자산
              </div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-semibold text-emerald-300 mb-1">
                {getWealthLabel(percentile)}
              </div>
              <div className="text-sm text-white/60">
                자산 등급
              </div>
            </div>
          </div>
        </div>

        {/* 하단 정보 */}
        <div className="text-center">
          <div className="text-white/60 text-base mb-2">
            World Bank 243개국 데이터 기반 분석
          </div>
          <div className="text-white/40 text-sm">
            paylens-kappa.vercel.app에서 더 자세한 분석 확인
          </div>
        </div>

        {/* 워터마크 */}
        <div className="absolute bottom-8 right-8 text-white/30 text-xs">
          Generated by PayLens
        </div>
      </div>
    </div>
  );
}